/*
 * @Author: MngYou
 * @Date: 2022-01-17 16:15:10
 * @LastEditTime: 2022-02-05 10:02:05
 * @FilePath: \wx\script\story\player.js
 */

(function(){
    var 主角数据 = {
        '名称':'主角',
        '姓名':'云行深',
        '头像':0x56020001,
        '动画':{
            '闲置动作':[0,1],
            '逃跑动作':[2,3,4,5,6,7,8,9,10,11],
            '死亡动作':[12,13,14,15],
            '普攻动作':[16,17,18,19,20,21,22,23,24,25],
            '拳掌起手式':[26,,27,28,29,30,31,32,33],
            '指法动作':[34,,35,36,37,38,39,40,41,42,43,44,45,46],
            '剑法动作':[48,49,50,51,52,53,54,55,56,57,58,59,60],
            '内功辅助':[63,64,65,66,67,68,69],
            '内功攻击':[70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99]
        },
        '动画特效':{},
        '坐标':{
            'x':360,
            'y':280
        },
        'url':{
            'png':'./images/act/spritesheet/主角.png',
            'json':'./images/act/spritesheet/主角.json'
        },
        '所有武学':{
            '拳':[
                {
                    '名称':'形意拳','图标':11,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/形意拳.png',
                        'json':'./images/eft/spritesheet/形意拳.json'
                    },
                },
                {
                    '名称':'罗汉拳','图标':12,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/罗汉拳.png',
                        'json':'./images/eft/spritesheet/罗汉拳.json'
                    },
                },
                {
                    '名称':'空明拳','图标':57,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/空明拳.png',
                        'json':'./images/eft/spritesheet/空明拳.json'
                    },
                },
                {
                    '名称':'太极拳','图标':58,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/太极拳.png',
                        'json':'./images/eft/spritesheet/太极拳.json'
                    },
                },
                {
                    '名称':'七伤拳','图标':59,
                    '坐标':{
                        'x':-280,
                        'y':-140
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/七伤拳.png',
                        'json':'./images/eft/spritesheet/七伤拳.json'
                    },
                },
                {
                    '名称':'绝学','图标':60,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/绝学.png',
                        'json':'./images/eft/spritesheet/绝学.json'
                    },
                },
            ],
            '掌':[
                {
                    '名称':'铁掌','图标':61,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/铁掌.png',
                        'json':'./images/eft/spritesheet/铁掌.json'
                    },
                },
                {
                    '名称':'绵掌','图标':62,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/绵掌.png',
                        'json':'./images/eft/spritesheet/绵掌.json'
                    },
                },
                {
                    '名称':'混元掌','图标':63,
                    '坐标':{
                        'x':-280,
                        'y':-140
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/混元掌.png',
                        'json':'./images/eft/spritesheet/混元掌.json'
                    },
                },
                {
                    '名称':'黯然销魂掌','图标':65,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/黯然销魂掌.png',
                        'json':'./images/eft/spritesheet/黯然销魂掌.json'
                    },
                },
                {
                    '名称':'天山六阳掌','图标':64,
                    '坐标':{
                        'x':-50,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/天山六阳掌.png',
                        'json':'./images/eft/spritesheet/天山六阳掌.json'
                    },
                },
                {
                    '名称':'降龙十八掌','图标':66,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/降龙十八掌.png',
                        'json':'./images/eft/spritesheet/降龙十八掌.json'
                    },
                },
            ],
            '指':[
                {
                    '名称':'弹指神通','图标':13,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/弹指神通.png',
                        'json':'./images/eft/spritesheet/弹指神通.json'
                    },
                },
                {
                    '名称':'一阳指','图标':14,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/一阳指.png',
                        'json':'./images/eft/spritesheet/一阳指.json'
                    },
                },
                {
                    '名称':'拈花指','图标':16,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/拈花指.png',
                        'json':'./images/eft/spritesheet/拈花指.json'
                    },
                },
                {
                    '名称':'参合指','图标':15,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/参合指.png',
                        'json':'./images/eft/spritesheet/参合指.json'
                    },
                },
                {
                    '名称':'六脉神剑','图标':18,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/六脉神剑.png',
                        'json':'./images/eft/spritesheet/六脉神剑.json'
                    },
                },
                {
                    '名称':'九阴神爪','图标':17,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/九阴神爪.png',
                        'json':'./images/eft/spritesheet/九阴神爪.json'
                    },
                },
            ],
            '剑':[
                {
                    '名称':'五岳剑法','图标':67,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/五岳剑法.png',
                        'json':'./images/eft/spritesheet/五岳剑法.json'
                    },
                },
                {
                    '名称':'金蛇剑法','图标':68,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/金蛇剑法.png',
                        'json':'./images/eft/spritesheet/金蛇剑法.json'
                    },
                },
                {
                    '名称':'太极剑','图标':69,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/太极剑.png',
                        'json':'./images/eft/spritesheet/太极剑.json'
                    },
                },
                {
                    '名称':'玄铁剑','图标':70,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/玄铁剑.png',
                        'json':'./images/eft/spritesheet/玄铁剑.json'
                    },
                },
                {
                    '名称':'独孤九剑','图标':71,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/独孤九剑.png',
                        'json':'./images/eft/spritesheet/独孤九剑.json'
                    },
                },
                {
                    '名称':'辟邪剑法','图标':72,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/辟邪剑法.png',
                        'json':'./images/eft/spritesheet/辟邪剑法.json'
                    },
                },
            ],
            '内':[
                {
                    '名称':'吐纳心法','图标':73,
                    '坐标':{
                        'x':-130,
                        'y':-50
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/吐纳心法.png',
                        'json':'./images/eft/spritesheet/吐纳心法.json'
                    },
                },
                {
                    '名称':'寒冰真气','图标':74,
                    '坐标':{
                        'x':-150,
                        'y':-120
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/寒冰真气.png',
                        'json':'./images/eft/spritesheet/寒冰真气.json'
                    },
                },
                {
                    '名称':'北冥神功','图标':75,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/北冥神功.png',
                        'json':'./images/eft/spritesheet/北冥神功.json'
                    },
                },
                {
                    '名称':'九阳神功','图标':76,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/九阳神功.png',
                        'json':'./images/eft/spritesheet/九阳神功.json'
                    },
                },
                {
                    '名称':'龙象般若功','图标':19,
                    '坐标':{
                        'x':-50,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/龙象般若功.png',
                        'json':'./images/eft/spritesheet/龙象般若功.json'
                    },
                },
                {
                    '名称':'太玄神功','图标':20,
                    '坐标':{
                        'x':-130,
                        'y':-100
                    },
                    'url':{
                        'png':'./images/eft/spritesheet/太玄神功.png',
                        'json':'./images/eft/spritesheet/太玄神功.json'
                    },
                },
            ],
        },
            ['姓']:'云',
            ['名']:'行深',
            ['门派']:'无门派',
            ['称号']:'江湖小混混',
            ['等级']:1,
            ['经验']:0,
            ['学点']:0,
            ['生命上限']:44,
            ['内力上限']:40,
            ['力道']:25,
            ['护体']:25,
            ['身法']:25,
            ['拳掌']:25,
            ['御剑']:25,
            ['暗器']:25,
            ['医疗']:15,
            ['用毒']:5,
            ['解毒']:15,
            ['悟性']:40,
            ['福缘']:30,
            ['声望']:0,
            ['侠义']:0,
    };
    
    主角数据.可用武学 = {
        '拳':[
            {'名称':'形意拳','可用':!true},
            {'名称':'罗汉拳','可用':!true},
            {'名称':'空明拳','可用':!true},
            {'名称':'太极拳','可用':!true},
            {'名称':'七伤拳','可用':!true},
            {'名称':'绝学','可用':false},
        ],
        '掌':[
            {'名称':'铁掌','可用':!true},
            {'名称':'绵掌','可用':!true},
            {'名称':'混元掌','可用':!true},
            {'名称':'黯然销魂掌','可用':!true},
            {'名称':'天山六阳掌','可用':!true},
            {'名称':'降龙十八掌','可用':!true},
        ],
        '指':[
            {'名称':'弹指神通','可用':!true},
            {'名称':'一阳指','可用':!true},
            {'名称':'拈花指','可用':!true},
            {'名称':'参合指','可用':!true},
            {'名称':'六脉神剑','可用':!true},
            {'名称':'九阴神爪','可用':!true},
        ],
        '剑':[
            {'名称':'五岳剑法','可用':!true},
            {'名称':'金蛇剑法','可用':!true},
            {'名称':'太极剑','可用':!true},
            {'名称':'玄铁剑','可用':!true},
            {'名称':'独孤九剑','可用':!true},
            {'名称':'辟邪剑法','可用':!true},
        ],
        '内':[
            {'名称':'吐纳心法','可用':!true},
            {'名称':'寒冰真气','可用':!true},
            {'名称':'北冥神功','可用':!true},
            {'名称':'九阳神功','可用':!true},
            {'名称':'龙象般若功','可用':!true},
            {'名称':'太玄神功','可用':!true},
        ],
    };
    this.playerData = 主角数据;
})();
